# -*- coding: utf-8 -*-
"""Least_squares_I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146creYltd62T-fmkbijLPorGTqOMpRrJ

#**Lab 6 - Least squares I**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab6"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Michael"

last_name="Morris"

# Enter your Math 215 section number in between the quotation marks. 

section_number="002"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER! 

BYUNetID="morrsis69"

"""**Import NumPy**"""

import numpy as np
import math as math

"""**Problem 1**"""

# Replace the values of 0 with the NumPy arrays from Problem 1.

X1 = np.array([[1,5],[1,10],[1,15],[1,20],[1,25],[1,30],[1,35],[1,40],[1,45],[1,50]])    

Y1 = np.array([3.33,4.43,4.39,5.23,5.67,6.06,7.01,7.16,8.03,8.78])

P1 = np.zeros((len(X1),2)) 
for i in range(len(P1)):
  P1[i][0] = X1[i][1]
  P1[i][1] = Y1[i]

print(P1)

"""**Problem 2**"""

# Replace the values of 0 with the normal equation coefficient matrix and normal equation right-hand side respectively from Problem 2.

normal_coef1 = X1.T@X1

normal_vect1 = X1.T@Y1

"""**Problem 3**"""

# Replace the value of 0 with the least squares solution beta1 you found in Problem 3.

beta1 = np.linalg.solve(normal_coef1,normal_vect1)

print(beta1)

# Define a function whose graph is the line of best fit.

def ls1_line(x): 
  v = beta1[0]
  a = beta1[1]
  return a*x+v

import matplotlib.pyplot as plt

# Construct your plot of ls1_line and the corresponding data points here. Put all of your code to create the plots inside the function below.

def create_plots1():
  xp = np.linspace(0,60,100)
  yp = ls1_line(xp)
  xe,ye = P1.T
  plt.plot(xp,yp,"#ff911a")
  plt.scatter(xe,ye)
  plt.show()
  return None
create_plots1()

# Replace the value of 0 with your prediction of the satellite's velocity at t=60.

pred1 = ls1_line(60)

"""**Problem 4**"""

# Replace the values of 0 with the NumPy arrays from Problem 4.

X2 = np.array([[5,25],[10,100],[15,225],[20,400],[25,625],[30,900],[35,1225],[40,1600],[45,2025],[50,2500]])    

Y2 = np.array([20.57,87.48,197.45,347.67,546.12,784.35,1066.02,1390.97,1761.85,2177.34])

P2 = np.zeros((len(X2),2))
for i in range(len(P2)):
  P2[i][0] = X2[i][0]
  P2[i][1] = Y2[i]

print(P2)

"""**Problem 5**"""

# Replace the values of 0 with the normal equation coefficient matrix and normal equation right-hand side, and least squares solution from Problem 5.

normal_coef2 = X2.T@X2    
normal_vect2 = X2.T@Y2 

beta2 = np.linalg.solve(normal_coef2,normal_vect2)

print(beta2)

"""**Problem 6**"""

# Define a function whose graph is the parabola of best fit.

def ls2_par(x): 
  v = beta2[0]
  A = beta2[1]
  return v*x + A*(x**2)

# Construct your plot of ls2_par and the corresponding data points here. Put all of your code to create the plots inside the function below.

def create_plots2():
  xp = np.linspace(0,60,100)
  yp = ls2_par(xp)
  xe,ye = P2.T
  plt.plot(xp,yp,"#ff911a")
  plt.scatter(xe,ye)
  plt.show()
  return None 
create_plots2()

# Replace the value of 0 with your prediction of the satellite's position at t=60.

pred2 = ls2_par(60)

"""**Problem 7**"""

t = np.array([[1,87.77],[1,224.70],[1,365.25],[1,686.95],[1,4332.62],[1,10759.20]])
for i in range(len(t)):
  t[i][1] = np.log(t[i][1])
r = np.array([0.389,0.724,1,1.524,5.2,9.510])
for j in range(len(r)):
  r[j] = np.log(r[j])
print(t)

# Replace the values of 0 with the NumPy arrays from Problem 7.

X3 = t   

Y3 = r

# Replace the values of 0 with the normal equation coefficient matrix and normal equation right-hand side from Problem 7.

normal_coef3 = X3.T@X3    

normal_vect3 = X3.T@Y3

# Replace the value of 0 with the least squares solution from Problem 7.

beta3 = np.linalg.solve(normal_coef3,normal_vect3)

print(beta3)

"""**Problem 8**"""

def ls3_kep(x):
  c = math.exp(beta3[0])
  a = beta3[1]
  return c*(x**a)

# Replace the values of 0 with your predictions for the semi-major axes of Uranus and Neptune.

pred_Uran = ls3_kep(30687.15) 

pred_Nept = ls3_kep(60190.03)

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""